### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xuefliang** [knightz1224/curl2pyreqs#1]
from curl2pyreqs import parseCurlString
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'parseCurlString' from 'curl2pyreqs' (C:\ProgramData\Anaconda3\lib\site-packages\curl2pyreqs\__init__.py)

**Comment by knightz1224** [comment]
Thank you for your report.
There are some mistakes in README.
Please try `from curl2pyreqs.ulti import parseCurlString` instead.
