### ISSUE TITLE
post请求不能正确解析data参数

### ISSUE THREAD

**Issue by haidongsong** [knightz1224/curl2pyreqs#2]
感谢大佬的分享，很好用。但是有个bug, post请求无法正确生成，缺少了data参数，比如下面这个curl。
来自https://www.iqihang.com/courselist这个网站
![image](https://user-images.githubusercontent.com/20490635/126752877-de0de62a-f945-4dca-9f8b-f466c131f299.png)

```
curl 'https://www.iqihang.com/api/v2/product/product-for-list/search-product-with-activity-info' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'EagleEye-SessionID: g0kC4r8qgkn0mp1m11py0ebeORme' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'EagleEye-pAppName: ah4dzf6mjw@7edb64cda121776' \
  -H 'EagleEye-TraceID: 61c61feb1627023911944100421776' \
  -H 'Origin: https://www.iqihang.com' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://www.iqihang.com/courselist' \
  -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'Cookie: Hm_lvt_2d1f9d97bbf037a2066e67f718a18093=1626772826; Hm_lvt_c0950c4366376d203c68fb5cde1b2c88=1626772826; DELOP_391=cfa4d910-af55-4112-b7d6-5103275635dc; SESSION=ZDhjY2IwNjUtMGMzZS00ZmQzLWE1ODAtZTBmMjNmYTAyYzZl; _bl_uid=b2k63r6sbRnu21j4Oe10rm6872e4; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22%24device_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22props%22%3A%7B%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D; gr_user_id=f9718ad6-d4d9-429e-86b6-21e61602daff; client_id=72827505; Hm_lpvt_2d1f9d97bbf037a2066e67f718a18093=1627021195; acw_tc=65c86a0916270239103797398eb2c86843ab2a245ffbc19ba920de87fdc170; Hm_lpvt_c0950c4366376d203c68fb5cde1b2c88=1627023912' \
  --data-raw '{"sort":"CREATE_TIME_DESC","year":"","catalogId":"","classType":"","pageIndex":0,"pageSize":9,"catalogIds":null}' \
  --compressed
```

**Comment by knightz1224** [comment]
之前我也发现了这个问题，将在0.4.0版本里修复，还会修复一些其他bug

**Comment by knightz1224** [comment]
已在0.4.0中修复。

> 感谢大佬的分享，很好用。但是有个bug, post请求无法正确生成，缺少了data参数，比如下面这个curl。
> 来自[https://www.iqihang.com/courselist这个网站](https://www.iqihang.com/courselist%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99)
> ![image](https://user-images.githubusercontent.com/20490635/126752877-de0de62a-f945-4dca-9f8b-f466c131f299.png)
> 
> ```
> curl 'https://www.iqihang.com/api/v2/product/product-for-list/search-product-with-activity-info' \
>   -H 'Connection: keep-alive' \
>   -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
>   -H 'Content-Type: application/json;charset=UTF-8' \
>   -H 'EagleEye-SessionID: g0kC4r8qgkn0mp1m11py0ebeORme' \
>   -H 'Accept: application/json, text/plain, */*' \
>   -H 'EagleEye-pAppName: ah4dzf6mjw@7edb64cda121776' \
>   -H 'EagleEye-TraceID: 61c61feb1627023911944100421776' \
>   -H 'Origin: https://www.iqihang.com' \
>   -H 'Sec-Fetch-Site: same-origin' \
>   -H 'Sec-Fetch-Mode: cors' \
>   -H 'Sec-Fetch-Dest: empty' \
>   -H 'Referer: https://www.iqihang.com/courselist' \
>   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
>   -H 'Cookie: Hm_lvt_2d1f9d97bbf037a2066e67f718a18093=1626772826; Hm_lvt_c0950c4366376d203c68fb5cde1b2c88=1626772826; DELOP_391=cfa4d910-af55-4112-b7d6-5103275635dc; SESSION=ZDhjY2IwNjUtMGMzZS00ZmQzLWE1ODAtZTBmMjNmYTAyYzZl; _bl_uid=b2k63r6sbRnu21j4Oe10rm6872e4; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22%24device_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22props%22%3A%7B%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D; gr_user_id=f9718ad6-d4d9-429e-86b6-21e61602daff; client_id=72827505; Hm_lpvt_2d1f9d97bbf037a2066e67f718a18093=1627021195; acw_tc=65c86a0916270239103797398eb2c86843ab2a245ffbc19ba920de87fdc170; Hm_lpvt_c0950c4366376d203c68fb5cde1b2c88=1627023912' \
>   --data-raw '{"sort":"CREATE_TIME_DESC","year":"","catalogId":"","classType":"","pageIndex":0,"pageSize":9,"catalogIds":null}' \
>   --compressed
> ```

**Comment by knightz1224** [comment]
> 感谢大佬的分享，很好用。但是有个bug, post请求无法正确生成，缺少了data参数，比如下面这个curl。
> 来自[https://www.iqihang.com/courselist这个网站](https://www.iqihang.com/courselist%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99)
> ![image](https://user-images.githubusercontent.com/20490635/126752877-de0de62a-f945-4dca-9f8b-f466c131f299.png)
> 
> ```
> curl 'https://www.iqihang.com/api/v2/product/product-for-list/search-product-with-activity-info' \
>   -H 'Connection: keep-alive' \
>   -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36' \
>   -H 'Content-Type: application/json;charset=UTF-8' \
>   -H 'EagleEye-SessionID: g0kC4r8qgkn0mp1m11py0ebeORme' \
>   -H 'Accept: application/json, text/plain, */*' \
>   -H 'EagleEye-pAppName: ah4dzf6mjw@7edb64cda121776' \
>   -H 'EagleEye-TraceID: 61c61feb1627023911944100421776' \
>   -H 'Origin: https://www.iqihang.com' \
>   -H 'Sec-Fetch-Site: same-origin' \
>   -H 'Sec-Fetch-Mode: cors' \
>   -H 'Sec-Fetch-Dest: empty' \
>   -H 'Referer: https://www.iqihang.com/courselist' \
>   -H 'Accept-Language: zh-CN,zh;q=0.9,en;q=0.8' \
>   -H 'Cookie: Hm_lvt_2d1f9d97bbf037a2066e67f718a18093=1626772826; Hm_lvt_c0950c4366376d203c68fb5cde1b2c88=1626772826; DELOP_391=cfa4d910-af55-4112-b7d6-5103275635dc; SESSION=ZDhjY2IwNjUtMGMzZS00ZmQzLWE1ODAtZTBmMjNmYTAyYzZl; _bl_uid=b2k63r6sbRnu21j4Oe10rm6872e4; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22%24device_id%22%3A%2217ac3376baf428-05ba3fb96f800d-34647600-2073600-17ac3376bb0fa7%22%2C%22props%22%3A%7B%22%24latest_referrer%22%3A%22%22%2C%22%24latest_referrer_host%22%3A%22%22%2C%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%A5%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%7D%7D; gr_user_id=f9718ad6-d4d9-429e-86b6-21e61602daff; client_id=72827505; Hm_lpvt_2d1f9d97bbf037a2066e67f718a18093=1627021195; acw_tc=65c86a0916270239103797398eb2c86843ab2a245ffbc19ba920de87fdc170; Hm_lpvt_c0950c4366376d203c68fb5cde1b2c88=1627023912' \
>   --data-raw '{"sort":"CREATE_TIME_DESC","year":"","catalogId":"","classType":"","pageIndex":0,"pageSize":9,"catalogIds":null}' \
>   --compressed
> ```

已在0.4.1版本中修复。

**Comment by haidongsong** [comment]
@knightz1224 感谢。
